/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.repositories;

import db.classes.Ground;
import db.mappers.IMapResultSetIntoEntity;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author Tmejs (mateusz.rzad@gmail.com)
 */
public class GroundRepository extends RepositoryBase<Ground> {

    private final static String TABLE_NAME = "GROUNDS";

    public GroundRepository(Connection connection, IMapResultSetIntoEntity<Ground> mapper) {
        super(connection, mapper);
    }

    @Override
    public String createTableSql() {
        return "create table "
                + tableName()
                + " ("
                + "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
                + "ADDRESS varchar2(100)";

    }

    @Override
    public String insertSql() {
        return "INSERT INTO "
                + tableName()
                + " (ADDRESS) "
                + "VALUES "
                + "(?)";
    }

    @Override
    public void insertPrepare(Ground entity) throws SQLException {
        insert.setString(1, entity.getAddress());
    }

    @Override
    public String updateSql() {
        return "UPDATE "
                + tableName()
                + " set (ADDRESS)="
                + "(?)";
    }

    @Override
    public void updatePrepare(Ground entity) throws SQLException {
        update.setString(1, entity.getAddress());
    }

    @Override
    public void deletePrepare(Ground entity) throws SQLException {
        delete.setInt(1, entity.getId());
    }

    @Override
    public void getPrepare(Ground entity) throws SQLException {
        selectById.setInt(1, entity.getId());
    }

    @Override
    public String tableName() {
        return TABLE_NAME;
    }

}
