/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.repositories;

import db.actions.IUnitOfWork;
import db.classes.Player;
import db.mappers.IMapResultSetIntoEntity;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author Tmejs (mateusz.rzad@gmail.com)
 */
public class PlayerRepository extends RepositoryBase<Player>{

    private final static String TABLE_NAME="PLAYERS";

    public PlayerRepository(Connection connection, IMapResultSetIntoEntity<Player> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    

    @Override
    public String createTableSql() {
        return "create table "
                + tableName()
                +" ("
                + "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
                + "NAME varchar(50),"
                + "SURNAME VARCHAR(50),"
                + "CONTACT_NUMBER VARCHAR(20) ,"
                + "USER_ID INT) ";
                //+ "FOREIGN KEY (USER_ID) REFERENCES USERS(ID))";
                
    }

        
    @Override
    public String insertSql() {
        return "INSERT INTO "
                + tableName()
                +" (NAME,SURNAME,CONTACT_NUMBER,USER_ID) "
                + "VALUES "
                + "(?,?,?,?)";
    }

    @Override
    public void insertPrepare(Player entity) throws SQLException{
        insert.setString(1, entity.getName());
        insert.setString(2, entity.getSurname());
        insert.setString(3,entity.getContactNumber());
        insert.setInt(4, entity.getUserId());
    }

    
    @Override
    public String updateSql() {
        return "UPDATE "
                + tableName()
                + " set (NAME,SURNAME,CONTACT_NUMBER,USER_ID)="
                + "(?,?,?,?)"
                + "where id = ?";
    }

    @Override
    public void updatePrepare(Player entity)  throws SQLException{
        insert.setString(1, entity.getName());
        insert.setString(2, entity.getSurname());
        insert.setString(3,entity.getContactNumber());
        insert.setInt(4, entity.getUserId());
        update.setInt(5, entity.getId());
    }
    
    
    @Override
    public String tableName() {
        return TABLE_NAME;
    }
    
    
}