/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.repositories;

import db.actions.IUnitOfWork;
import db.classes.Team;
import db.mappers.IMapResultSetIntoEntity;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Tmejs (mateusz.rzad@gmail.com)
 */
public class TeamRepository extends RepositoryBase<Team> implements ITeamRepository {

    private final static String TABLE_NAME = "TEAMS";

    public TeamRepository(Connection connection, IMapResultSetIntoEntity<Team> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    @Override
    public Team getTeamByUserId(Integer id) {
        PreparedStatement getById;
        try {
            getById = connection.prepareStatement("select * from " + tableName() + " where ID_USER =?");
            getById.setInt(1, id);
            ResultSet rs = getById.executeQuery();
            if (rs.next()) {
                return mapper.map(rs);
            } else {
                return null;
            }

        } catch (SQLException e) {
            return null;
        }
    }

    @Override
    public String createTableSql() {
        return "create table "
                + tableName()
                + " ("
                + "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
                + "ID_USER INT,"
                + "NAME varchar(20),"
                + "FOREIGN KEY (ID_USER) REFERENCES USERS(ID))";

    }

    @Override
    public String insertSql() {
        return "INSERT INTO "
                + tableName()
                + " (ID_USER,NAME) "
                + "VALUES "
                + "(?,?)";
    }

    @Override
    public void insertPrepare(Team entity) throws SQLException {
        insert.setInt(1, entity.getIdUsera());
        insert.setString(2, entity.getName());
    }

    @Override
    public String updateSql() {
        return "UPDATE "
                + tableName()
                + " set (NAME,ID_USER)="
                + "(?,?)"
                + "where id = ?";
    }

    @Override
    public void updatePrepare(Team entity) throws SQLException {
        update.setString(1, entity.getName());
        update.setInt(2, entity.getIdUsera());
        update.setInt(3, entity.getId());

    }

    @Override
    public String tableName() {
        return TABLE_NAME;
    }

}
