/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.repositories;

import db.actions.IUnitOfWork;
import db.classes.TeamMember;
import db.mappers.IMapResultSetIntoEntity;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author Tmejs (mateusz.rzad@gmail.com)
 */
public class TeamMemberRepository  extends RepositoryBase<TeamMember>{
    
    
    private final static String TABLE_NAME = "TEAM_PLAYERS";

    public TeamMemberRepository(Connection connection, IMapResultSetIntoEntity<TeamMember> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

  

    

    @Override
    public String createTableSql() {
        return "create table "
                + tableName()
                + " ("
                + "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
                + "TEAM_ID int,"
                + "PLAYER_ID int,"
                + "IS_CAPTAIN BOOLEAN,"
                + "FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID),"
                + "FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(ID))";

    }

    @Override
    public String insertSql() {
        return "INSERT INTO "
                + tableName()
                + " (TEAM_ID,PLAYER_ID,IS_CAPTAIN) "
                + "VALUES "
                + "(?,?,?)";
    }

    @Override
    public void insertPrepare(TeamMember entity) throws SQLException {
        insert.setInt(1, entity.getTeamId());
        insert.setInt(2, entity.getPlayerId());
        insert.setBoolean(3, entity.getIsCaptain());
    }

    @Override
    public String updateSql() {
        return "UPDATE "
                + tableName()
                + " set (TEAM_ID,PLAYER_ID,IS_CAPTAIN)="
                + "(?,?,?)"
                + "where id = ?";
    }

    @Override
    public void updatePrepare(TeamMember entity) throws SQLException {
        insert.setInt(1, entity.getTeamId());
        insert.setInt(2, entity.getPlayerId());
        insert.setBoolean(3, entity.getIsCaptain());
        insert.setInt(4, entity.getId());
    }

    @Override
    public String tableName() {
        return TABLE_NAME;
    }
    
}
