/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.repositories;

import db.actions.IUnitOfWork;
import db.classes.Team;
import db.classes.Tournament;
import db.mappers.IMapResultSetIntoEntity;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Tmejs (mateusz.rzad@gmail.com)
 */
public class TournamentRepository extends RepositoryBase<Tournament> {

    private final static String TABLE_NAME = "TOURNAMENTS";

    public TournamentRepository(Connection connection, IMapResultSetIntoEntity<Tournament> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    

    

    @Override
    public String createTableSql() {
        return "create table "
                + tableName()
                + " ("
                + "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
                + "TOURNAMENT_DATE DATE,"
                + "ORGANIZER_ID INT ,"
                + "ADDRESS VARCHAR(60) ,"
                + "NAME VARCHAR(60) ,"
                + "FOREIGN KEY (ORGANIZER_ID) REFERENCES USERS(ID))";

    }

    @Override
    public String insertSql() {
        return "INSERT INTO "
                + tableName()
                + " (TOURNAMENT_DATE,ORGANIZER_ID,ADDRESS,NAME) "
                + "VALUES "
                + "(?,?,?,?)";
    }

    @Override
    public void insertPrepare(Tournament entity) throws SQLException {
        insert.setDate(1, entity.getStartDate());
        insert.setInt(2, entity.getOrganizerPersonId());
        insert.setString(3, entity.getAddress());
        insert.setString(4, entity.getName());
        
    }

    @Override
    public String updateSql() {
        return "UPDATE "
                + tableName()
                + " set (TOURNAMENT_DATE,ORGANIZER_ID,ADDRESS,NAME)="
                + "(?,?,?,?)"
                + "where id = ?";
    }

    @Override
    public void updatePrepare(Tournament entity) throws SQLException {
        update.setDate(1, entity.getStartDate());
        update.setInt(2, entity.getOrganizerPersonId());
        update.setString(3, entity.getAddress());
        update.setString(4, entity.getName());
        update.setInt(5, entity.getId());
    }

    @Override
    public String tableName() {
        return TABLE_NAME;
    }
}
