/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.repositories;

import db.actions.IUnitOfWork;
import db.classes.TournamentTeam;
import db.mappers.IMapResultSetIntoEntity;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author Tmejs (mateusz.rzad@gmail.com)
 */
public class TournamentTeamRepository extends RepositoryBase<TournamentTeam> {

    public TournamentTeamRepository(Connection connection, IMapResultSetIntoEntity<TournamentTeam> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    

    private final static String TABLE_NAME = "TORUNAMENT_TEAMS";

    @Override
    public String createTableSql() {
        return "create table "
                + tableName()
                + " ("
                + "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
                + "TEAM_ID int,"
                + "TOURNAMENT_ID int,"
                + "FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID),"
                + "FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENTS(ID))";

    }

    @Override
    public String insertSql() {
        return "INSERT INTO "
                + tableName()
                + " (TEAM_ID,TOURNAMENT_ID) "
                + "VALUES "
                + "(?,?)";
    }

    @Override
    public void insertPrepare(TournamentTeam entity) throws SQLException {
        insert.setInt(1, entity.getTeamId());
        insert.setInt(2, entity.getTournamentID());
    }

    @Override
    public String updateSql() {
        return "UPDATE "
                + tableName()
                + " set (TEAM_ID,TOURNAMENT_ID)="
                + "(?,?)"
                + "where id = ?";
    }

    @Override
    public void updatePrepare(TournamentTeam entity) throws SQLException {
        insert.setInt(1, entity.getTeamId());
        insert.setInt(2, entity.getTournamentID());
        insert.setInt(3, entity.getId());
    }

    @Override
    public String tableName() {
        return TABLE_NAME;
    }

}
